DEMO_USER = {
    "id": 1,
    "email": "soypark777@gmail.com",
    "nickname": "SoyDancer",
    "avatar_id": "avatar_001",
    "points": 2480,
    "is_admin": False,
    "status": "active",
    "rank": "dancer",
    "streak_days": 7,
}

DEMO_ADMIN = {
    "id": 9001,
    "email": "admin@kpopdance.local",
    "nickname": "DanceAdmin",
    "avatar_id": "avatar_001",
    "points": 9999,
    "is_admin": True,
    "status": "active",
    "rank": "legend",
    "streak_days": 0,
    "created_at": "2024-11-01T00:00:00Z",
}

DEMO_DANCE_REFERENCES = [
    {
        "id": 1,
        "title": "Neon Step Beginner",
        "artist_name": "My Avatar Dance Master",
        "difficulty": "easy",
        "duration_seconds": 16,
        "thumbnail_url": "/mock/thumbs/neon-step.jpg",
        "preview_video_url": None,
        "reference_json_path": "/storage/dance_reference/neon-step.json",
        "created_at": "2026-05-12T00:00:00Z",
    },
    {
        "id": 2,
        "title": "Retro Groove Easy",
        "artist_name": "My Avatar Dance Master",
        "difficulty": "easy",
        "duration_seconds": 16,
        "thumbnail_url": "/mock/thumbs/retro-groove.jpg",
        "preview_video_url": None,
        "reference_json_path": "/storage/dance_reference/retro-groove.json",
        "created_at": "2026-05-12T00:00:00Z",
    },
    {
        "id": 3,
        "title": "Idol Intro Basic",
        "artist_name": "My Avatar Dance Master",
        "difficulty": "easy",
        "duration_seconds": 16,
        "thumbnail_url": "/mock/thumbs/idol-intro.jpg",
        "preview_video_url": None,
        "reference_json_path": "/storage/dance_reference/idol-intro.json",
        "created_at": "2026-05-12T00:00:00Z",
    },
]

DEMO_RECENT_SESSIONS = [
    {
        "id": 101,
        "user_id": 1,
        "dance_reference_id": 1,
        "dance_reference": DEMO_DANCE_REFERENCES[0],
        "started_at": "2025-04-15T10:00:00Z",
        "ended_at": "2025-04-15T10:04:00Z",
        "total_score": 85,
        "lowest_section_score": 71,
        "unlock_avatar_render": True,
        "session_status": "completed",
        "created_at": "2025-04-15T10:00:00Z",
    },
    {
        "id": 100,
        "user_id": 1,
        "dance_reference_id": 2,
        "dance_reference": DEMO_DANCE_REFERENCES[1],
        "started_at": "2025-04-14T11:30:00Z",
        "ended_at": "2025-04-14T11:33:30Z",
        "total_score": 72,
        "lowest_section_score": 58,
        "unlock_avatar_render": False,
        "session_status": "completed",
        "created_at": "2025-04-14T11:30:00Z",
    },
    {
        "id": 99,
        "user_id": 1,
        "dance_reference_id": 3,
        "dance_reference": DEMO_DANCE_REFERENCES[2],
        "started_at": "2025-04-13T09:00:00Z",
        "ended_at": "2025-04-13T09:05:00Z",
        "total_score": 91,
        "lowest_section_score": 82,
        "unlock_avatar_render": True,
        "session_status": "completed",
        "created_at": "2025-04-13T09:00:00Z",
    },
]
